name: Karma Releases

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Project
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/app-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o dist/app-linux-arm64
          GOOS=darwin GOARCH=amd64 go build -o dist/app-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o dist/app-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o dist/app-windows-amd64.exe

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            dist/app-linux-amd64
            dist/app-linux-arm64
            dist/app-darwin-amd64
            dist/app-darwin-arm64
            dist/app-windows-amd64.exe
